<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hgon_species"
 *
 * Auto generated by Extension Builder 2024-04-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'HgonSpecies',
    'description' => 'Shows species lists',
    'category' => 'plugin',
    'author' => 'Maximilian Fäßler',
    'author_email' => 'maximilian@faesslerweb.de',
    'state' => 'beta',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '13.4.2',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-13.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
